### ISSUE TITLE
Rotate delivery script log

### ISSUE THREAD

**Issue by TanyaGaleyev** [SuselMan/PianoZ#12]
Delivery script log now grows slowly but it is not bounded.

**Comment by stytz** [comment]
Wtf is delivery script log?

**Comment by TanyaGaleyev** [comment]
It is task for me. On a machine which deploys our app to preview a script runs. I call it delivery script. The script writes logs, but log file size is unbounded at the moment.

**Comment by TanyaGaleyev** [comment]
Currently log is rotated using standard **logrotate** configuration. Delivery script utilize **syslog** with tag **auto-deploy**. There is no special syslog configuration and so all entries are written to _/var/log/messages_.

**Comment by TanyaGaleyev** [comment]
May be **logrotate** is not robust enough if log grows very fast, because it use significant interval between executions (as I know -- 1 day). **rsyslog** is capable to perform rotation when log file reaches exact size (using **outchannel**), but unfortunately additional SELinux configuration is needed.
