### ISSUE TITLE
Draw notes sheet

### ISSUE THREAD

**Issue by TanyaGaleyev** [SuselMan/PianoZ#6]

**Comment by stytz** [comment]
Some options on how to implement music sheets:

| Library | Input | Output |
| --- | --- | --- |
| http://abcjs.net/ | ABC notation | SVG |
| http://www.vexflow.com/ | its own VexTab notation + github plugins for other notations | Canvas, SVG |
| http://www.musicxml-viewer.com/ | MusicXML | Canvas |

https://github.com/adius/awesome-sheet-music - just some links to look at
http://lilypond.org/ - we really should pay attention to this one

**Comment by stytz** [comment]
Closed with pull-request #7.
